services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tech-challenge-backend
    ports:
      - "8080:8080"
      -  "8787:8787"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tech_challenge_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db

  db:
    volumes:
      - tech_challenge_db-data:/var/lib/postgresql/data
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: tech_challenge_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

volumes:
  tech_challenge_db-data:
